version: '3'

services:
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: backendtest
      MYSQL_DATABASE: backendtest
      MYSQL_USER: backendtest
      MYSQL_PASSWORD: backendtest
      MYSQL_ROOT_HOST: '%'
