version: '3'

services:
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: backendtest
      MYSQL_DATABASE: backendtest
      MYSQL_USER: backendtest
      MYSQL_PASSWORD: backendtest
      MYSQL_ROOT_HOST: '%'
